import noodle2 from "../assets/noodle2.svg";
import noodle3 from "../assets/noodle3.svg";
import noodle4 from "../assets/noodle4.svg";
import noodle5 from "../assets/noodle5.svg";
import leaf from "../assets/leaf.svg";

 export const dishes = [
  {
    id: 1,
    name: "Healthy noodle with spinach leaf",
    oldPrice: 32,
    price: 25,
    available: "22 Bowls available",
    sizes: ["S", "M", "L"],
    image: leaf,
    category: "our",
    typ: "takeaway",
  },
  {
    id: 2,
    name: "Hot spicy fried rice with omelet",
    oldPrice: 32,
    price: 25,
    available: "13 Bowls available",
    sizes: ["S", "M", "L"],
    image: noodle2,
    category: "today",
    typ: "dine-in",
  },
  {
    id: 3,
    name: "Spicy instant noodle  omelette",
    oldPrice: 32,
    price: 25,
    available: "17 Bowls available",
    sizes: ["S", "M", "L"],
    image: noodle3,
    category: "south",
    typ: "takeaway",
  },
  {
    id: 4,
    name: "Healthy noodle with spinach leaf",
    oldPrice: 32,
    price: 25,
    available: "22 Bowls available",
    sizes: ["S", "M", "L"],
    image: noodle4,
    category: "south",
    typ: "takeaway",
  },
  {
    id: 5,
    name: "Hot spicy fried rice with omelet",
    oldPrice: 32,
    price: 25,
    available: "13 Bowls available",
    sizes: ["S", "M", "L"],
    image: noodle5,
    category: "today",
    typ: "takeaway",
  },
  {
    id: 6,
    name: "Hot spicy fried rice with omelet",
    oldPrice: 32,
    price: 25,
    available: "13 Bowls available",
    sizes: ["S", "M", "L"],
    image: noodle2,
    category: "our",
    typ: "dine-in",
  },
  {
    id: 7,
    name: "Spicy instant noodle with omelette",
    oldPrice: 32,
    price: 25,
    available: "17 Bowls available",
    sizes: ["S", "M", "L"],
    image: noodle3,
    category: "today",
    typ: "dine-in",
  },
  {
    id: 8,
    name: "Healthy noodle with spinach leaf",
    price: 25,
    available: "22 Bowls available",
    sizes: ["S", "M", "L"],
    image: noodle4,
    category: "our",
    typ: "takeaway",
  },
  {
    id: 9,
    name: "Hot spicy fried rice with omelet",
    price: 25,
    available: "13 Bowls available",
    sizes: ["S", "M", "L"],
    image: noodle5,
    category: "south",
    typ: "takeaway",
  },
  {
    id: 10,
    name: "Healthy noodle with spinach leaf",
    oldPrice: 32,
    price: 25,
    available: "22 Bowls available",
    sizes: ["S", "M", "L"],
    image: leaf,
    category: "today",
    typ: "dine-in",
  },
  {
    id: 11,
    name: "Healthy noodle with spinach leaf",
    oldPrice: 32,
    price: 25,
    available: "22 Bowls available",
    sizes: ["S", "M", "L"],
    image: leaf,
    category: "our",
    typ: "takeaway",
  },
];